name: Build and Release

env:
  RELEASE: 5.0.0.43
  OS: ubuntu-latest

on:
  push:
    tags:
      - '*'
    branches:
      - main
    paths-ignore:
      - .vscode/**
      - icon_src/**
      - pictures/**
      - README.md
      - LICENSE
      - pyrightconfig.json
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [aarch64, armv7hl, i486]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # Caching Docker images is not ready yet, see
    # https://github.com/storeman-developers/harbour-storeman-installer/blob/devel/cache-docker-images_github-ci.md
    #- name: Cache Docker images of the Sailfish-SDK
    #  id: cache-sdk
    #  uses: actions/cache@v3
    #  with:
    #    path: $GITHUB_WORKSPACE/…
    #    key: cache

    - name: Prepare
      run: |
        sed -i 's/%define package_library "no"/%define package_library "yes"/g' rpm/SailDiscord.spec
        mkdir RPMS

    - name: Build ${{ matrix.arch }} on ${{ env.RELEASE }}
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE }}
        arch: ${{ matrix.arch }}

    - uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.arch }}-SailfishOS-${{ env.RELEASE }}
        path: RPMS/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'v')

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: binaries
        pattern: build-*
        merge-multiple: true

    - name: Create release
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        gh release create "$tag_name" "${assets[@]}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}